language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: main
env:
  global:
    secure: S7vOk9SXUcvS+/9d7UeAkq9pr+ymAuU+hoJYASfiWAM9qWECpaLCiMttJUo4knolmOzoqPUsWtuZLvmSyJfF+pb13p/XL7xriIIuvs1Av7vpKlBnkryWEW9WSd0vY3zR5hMZah5SVPKFSQuNlRqkzEFF3ln14NDTU89qOnwPfS4ZntEnUvIUJaAT1fdQV3NBL/YqMuyLl3EBKuAZ01NTh3/60uam7VYunmz1mM3RyAllC15Pe4+oMjXaXmvloVQJ5uB97sCSL4SZ/5I3k6tBVNh4+irgT++CV6wlDmqSm+MKGJCuAidujQuArtoU7vqlChQHJ7DpwnS02S8jBKN/s4W/WTsbuDNUuq+Qu9VWrz1rrb7vB37xgJ/WYUiWOo8FD+e75DZcIr3CvLNOJMU2SHr6eHGETFbDvXTxQUjZMerAja1cxxAoXths6JaGZDciL2Q94W8J19KTdnv4VEwXU2W4ZuflC3DbR07BXQsYQmUeYmNKTHe4amW0yLh0Og8s+pXKItVszUq1K3FLOrfA/Yz9ZZVNVUgo++Zuk5t1/y1q8qIis3gCPP3v8fo955QlshWEg3EL60Qe6YwTeWjt6CH3LRxRmeQz7qU394meRTy67DSjM4Wbx3QMCtGBPybfNh+Wx9mhM/CvPn/qfgWCFpjP66ycCySJ7wQrncIwv04=
