language: node_js
node_js:
- stable
cache: npm
before_script:
- npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target-branch: gh-pages
  local_dir: dist