language: node_js
node_js:
- stable
cache: npm
before_script:
- npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target-branch: gh-pages
  local_dir: dist
env:
  global:
    secure: AQ5Cja7wRTgWAFnnR+Geop/FuKzqp42AFue20JZ/SvCdINZQF2RLdpmWE/FVq/JhL2u59QMItqQdYgKr2cWfCjFZ3hYouOJV9XNsXyGxteGD9DtmeXPDOnCVFgX4BbGGZdiPQbNcqgJvqKIUwkZfFwslVCulffG3jXCYDir7N9urheXDx7aTaz6NhQQycjjlf8lv9JWuBpHtL48Qbxn+fW8A18BZJm0jMxBhiUjttSOCMaOAsmifn3OybFQhtlhlv3ipsrGXNAkzPqHUkZGVM9oUSkRaPmKAxQIAYXLxFg7Jrw79wcYHKO9lx5sxqUwfWyBSMTmF/m0GzlBUJvCK1Ufya4WqMpjI+5RPqC7bgMloPJAbu6lo4f9R9MqIQz1/v6Qj+UIZ58VQGLzxiipELCtM1iyFVWd6WHo7pZMTx8kBi/APg+NfoNQnDfK+jRQPYK/mjJjWcfIoC09sBe5yKnflaj5yt4279VoO3z6XavevS/yuH7FT8y7xzGz2ra54tvIAy3TeHAS3SQmAZ2UH+G4xX2/z3jDCksm9Vxp1yUMeT/SwUev7JyoY6zsqvt9XgF+kWKXmJUMo8QKUj6Kj/UgK5oGuiv5lLurYPpR062MSQxW/B99ioXqatMc1TXc9hzKugABE7DR2eHk48au/desNaoJGUmI26KcshPwT/Zw=
